### ISSUE TITLE
todo for initial release

### ISSUE THREAD

**Issue by clarkevans** [rbt-lang/DataKnots.jl#2]
# Scope of the Release

The purpose of our first release is to create the bare minimum system which allows us to demonstrate the basic operations of Query Combinators realized in the Julia language.   The scope is not to provide complete or performant system.  In particular, it will not have any way data into the system, but this will be in the roadmap for later releases.  This release contain a tutorial, a few demonstrations, reference documentation, and test suite.

# Deliverables for this Release

- [ ] Prune & Document Public API (see below)
- [ ] Produce a few Demonstrations
- [ ] Make a Roadmap of Future Releases 
- [ ] Explain Lifting and provide copious examples
- [ ] Clarify Record/Given/Field/Recall and lookup semantics

## Demonstrations

- [ ] Filesystem
- [ ] Data Simulator
- [ ] Hard-Coded Dataset

#  Initial Public API

## DataKnot Operations

- [ ] `DataKnot`
- [ ] `@VectorTree`
- [ ] `query()`
- [ ] JSON Output

## Querying

- [ ] `query()`

## Combinators

- [ ] `It`
- [ ] `Given` / `Recall`
- [ ] `Record` / `Field`
- [ ] `Count`
- [ ] `Repeat`
- [ ] `Filter`
- [ ] `Take` / `Drop`

## Lifting Combinators

- [ ] Regular Functions
- [ ] Aggregate Functions
- [ ] Plural Functions
- [ ] Broadcasting

# Future Releases

- Loading XML
- Loading CSV
- Loading JSON
- PostgreSQL
- SQLite
- Select 
- Framing
- Sorting
- Grouping
- Weave & Graft
- Connect By
- Cube & Rollup
- Macro Language
- Common Subexpression Elimination
